Global:
  use_gpu: true
  epoch_num: 300
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ../output/bankcard/rec_chinese_common_v2.0/v3-train
  save_epoch_step: 30
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [ 0, 85 ]
  cal_metric_during_train: True
  pretrained_model: ../pretrained_model/ch_ppocr/ch_ppocr_server_v2.0_rec_train/best_accuracy.pdparams
  checkpoints: ../output/bankcard/rec_chinese_common_v2.0/v3-train/best_accuracy.pdparams
  save_inference_dir: ../output/bankcard/rec_chinese_common_v2.0/inference
  use_visualdl: true
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: ../cust-config/bank/rec-ppocr/ppocr_bankcard_keys_v1.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: True
  save_res_path: ../output/bankcard/rec_chinese_common_v2.0/rec/predicts_chinese_common_v2.0.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: 'L2'
    factor: 0.00004

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0.00004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ../train_data/
    label_file_list:
      - ../train_data/bank/rec/train.txt
      - ../train_data/bank-axa/rec/train.txt
    ratio_list:
      - 1.0
      - 1.0
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug:
          use_tia: True
          aug_prob: 0.4
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [ 3, 32, 320 ]
      - KeepKeys:
          keep_keys: [ 'image', 'label', 'length' ] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../train_data/
    label_file_list:
      - ../train_data/bank-axa/rec/test.txt
      - ../train_data/bank/rec/test.txt
    ratio_list:
      - 1.0
      - 1.0
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [ 3, 32, 320 ]
      - KeepKeys:
          keep_keys: [ 'image', 'label', 'length' ] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 8
